import { SUPABASE_URL } from './config.js';
const urlParams=new URLSearchParams(window.location.search);let token=urlParams.get('token')||localStorage.getItem('admin_auth_token');if(token)localStorage.setItem('admin_auth_token',token);
const $=id=>document.getElementById(id),businessTitleEl=$('business-title'),subtitleEl=$('dashboard-subtitle'),statusEl=$('status-message'),canvas=$('standee-canvas'),hiddenQrDiv=$('qrcode-hidden'),downloadBtn=$('download-standee-btn'),feedbackList=$('feedback-list');let currentQr=null,currentBusiness=null,currentFeedback=[];
function setStatus(m,t='loading'){if(statusEl){statusEl.textContent=m;statusEl.className=`status ${t}`}}
async function adminApi(action='dashboard',payload={}){const r=await fetch(`${SUPABASE_URL}/functions/v1/admin_api`,{method:'POST',headers:{'Content-Type':'application/json','x-admin-token':token},body:JSON.stringify({action,token,...payload})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||'Admin authorization failed');return x}
async function loadDashboard(){try{if(!token){setStatus('Access denied. No admin token was provided.','error');if(subtitleEl)subtitleEl.textContent='Open the Admin page using your business token.';return}setStatus('Authenticating...');const result=await adminApi();const business=result.business;if(!business){localStorage.removeItem('admin_auth_token');setStatus('Unauthorized. Invalid business token.','error');return}currentBusiness=business;if(businessTitleEl)businessTitleEl.textContent=business.business_name||'WonderQR Business';const qrRelation=Array.isArray(business.qr_codes)?business.qr_codes[0]:business.qr_codes;const qrCode=qrRelation?.code||business.qr_code||null;currentQr=qrCode;updateSummary(business,qrCode,result.feedback||[]);window.dispatchEvent(new CustomEvent('wonderqr:admin-ready',{detail:{business,qrCode}}));populateEditForm(business);if(qrCode){setStatus(`Connected • QR Code: ${qrCode}`,'success');if(subtitleEl)subtitleEl.textContent=`QR Code: ${qrCode}`;await generateStandee(qrCode,business)}else{setStatus('Business found, but no QR code is assigned.','error')}currentFeedback=(result.feedback||[]).filter(f=>Number(f.rating)>=1&&Number(f.rating)<=4);renderFeedback('all');loadSocialLinks(business)}catch(e){console.error(e);setStatus(e.message||'Unable to load Admin dashboard.','error');if(subtitleEl)subtitleEl.textContent='Please check the Admin link and try again.'}}
function updateSummary(business,qrCode,feedbacks){let privateCount=0;feedbacks.forEach(f=>{const r=Number(f.rating);if(r>=1&&r<=4)privateCount++});if($('stat-feedback'))$('stat-feedback').textContent=privateCount;if($('stat-qr'))$('stat-qr').textContent=qrCode||'—';if($('feedback-count'))$('feedback-count').textContent=`(${privateCount})`;if($('profile-business'))$('profile-business').textContent=business.business_name||'—';if($('profile-qr'))$('profile-qr').textContent=qrCode||'—';if($('profile-status'))$('profile-status').textContent=business.active===false?'Inactive':'Active'}
const editableFields=['business_name','owner_name','phone_number','whatsapp_number','instagram_url','youtube_url','facebook_url','justdial_url','zomato_url','swiggy_url','pinterest_url','x_url'];
const editFieldIds={business_name:'edit-business-name',owner_name:'edit-owner-name',phone_number:'edit-phone',whatsapp_number:'edit-whatsapp',instagram_url:'edit-instagram',youtube_url:'edit-youtube',facebook_url:'edit-facebook',justdial_url:'edit-justdial',zomato_url:'edit-zomato',swiggy_url:'edit-swiggy',pinterest_url:'edit-pinterest',x_url:'edit-x'};
function editEl(k){return $(editFieldIds[k])}
function populateEditForm(b){editableFields.forEach(k=>{const el=editEl(k);if(el)el.value=b[k]||''});clearEditMessage()}
function clearEditMessage(){const el=$('edit-save-message');if(el){el.textContent='';el.className='save-message'}}
function setEditMessage(m,t){const el=$('edit-save-message');if(el){el.textContent=m;el.className=`save-message ${t||''}`}}
function selectEditCategory(category){document.querySelectorAll('.edit-category-wrap').forEach(w=>w.classList.toggle('active',w.dataset.categoryWrap===category));document.querySelectorAll('.edit-category').forEach(b=>b.classList.toggle('active',b.dataset.category===category));clearEditMessage()}
function closeEditPanel(){const panel=$('edit-panel');if(panel)panel.classList.remove('open');document.querySelectorAll('.edit-category-wrap').forEach(w=>w.classList.remove('active'));document.querySelectorAll('.edit-category').forEach(b=>b.classList.remove('active'));clearEditMessage()}
function toggleEditPanel(){const panel=$('edit-panel');if(!panel)return;const opening=!panel.classList.contains('open');panel.classList.toggle('open',opening);if(opening){selectEditCategory('business');panel.scrollIntoView({behavior:'smooth',block:'nearest'})}else closeEditPanel()}
function validateEdit(data){if(!data.business_name.trim())return'Business name is required.';for(const k of editableFields.filter(x=>x.endsWith('_url'))){const v=data[k].trim();if(!v)continue;try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol))throw 0}catch{return`Please enter a valid ${k.replace('_url','').replace('_',' ')} URL.`}}for(const k of ['phone_number','whatsapp_number']){const v=data[k].trim();if(v&&!/^[+()\d\s.-]{7,30}$/.test(v))return`Please enter a valid ${k==='phone_number'?'phone':'WhatsApp'} number.`}return null}
async function saveBusiness(){clearEditMessage();const data={};editableFields.forEach(k=>{const el=editEl(k);data[k]=el?el.value.trim():''});const error=validateEdit(data);if(error){setEditMessage(error,'error');return}const btn=$('save-business-btn');if(btn)btn.disabled=true;setEditMessage('Saving...');try{const result=await adminApi('update_profile',data);if(!result.business)throw new Error('Business profile was not returned after saving.');currentBusiness=result.business;if(businessTitleEl)businessTitleEl.textContent=currentBusiness.business_name||'WonderQR Business';updateSummary(currentBusiness,currentQr,currentFeedback);window.dispatchEvent(new CustomEvent('wonderqr:admin-ready',{detail:{business:currentBusiness,qrCode:currentQr}}));loadSocialLinks(currentBusiness);await generateStandee(currentQr,currentBusiness);populateEditForm(currentBusiness);setEditMessage('Business information updated successfully.','success');setStatus(`Connected • QR Code: ${currentQr}`,'success');setTimeout(closeEditPanel,900)}catch(e){console.error(e);setEditMessage(e.message||'Unable to save business information.','error')}finally{if(btn)btn.disabled=false}}
$('open-edit-btn')?.addEventListener('click',toggleEditPanel);document.querySelectorAll('.edit-category').forEach(btn=>btn.addEventListener('click',()=>selectEditCategory(btn.dataset.category)));$('save-business-btn')?.addEventListener('click',saveBusiness);$('cancel-business-btn')?.addEventListener('click',()=>{if(currentBusiness)populateEditForm(currentBusiness);closeEditPanel()});
function loadSocialLinks(b){const el=$('social-links');if(!el)return;const links=[];if(b.instagram_url)links.push(`<a href="${safeUrl(b.instagram_url)}" target="_blank" rel="noopener">Instagram</a>`);if(b.youtube_url)links.push(`<a href="${safeUrl(b.youtube_url)}" target="_blank" rel="noopener">YouTube</a>`);if(b.facebook_url)links.push(`<a href="${safeUrl(b.facebook_url)}" target="_blank" rel="noopener">Facebook</a>`);if(b.whatsapp_number)links.push(`<a href="https://wa.me/${String(b.whatsapp_number).replace(/\D/g,'')}" target="_blank" rel="noopener">WhatsApp</a>`);if(b.phone_number)links.push(`<a href="tel:${String(b.phone_number).replace(/[^+\d]/g,'')}">Call</a>`);if(b.justdial_url)links.push(`<a href="${safeUrl(b.justdial_url)}" target="_blank" rel="noopener">Justdial</a>`);if(b.zomato_url)links.push(`<a href="${safeUrl(b.zomato_url)}" target="_blank" rel="noopener">Zomato</a>`);if(b.swiggy_url)links.push(`<a href="${safeUrl(b.swiggy_url)}" target="_blank" rel="noopener">Swiggy</a>`);if(b.pinterest_url)links.push(`<a href="${safeUrl(b.pinterest_url)}" target="_blank" rel="noopener">Pinterest</a>`);if(b.x_url)links.push(`<a href="${safeUrl(b.x_url)}" target="_blank" rel="noopener">X</a>`);el.innerHTML=links.length?links.join(''):'<span class="hint">No social or contact links added.</span>'}
