let deferredPrompt=null;
const installButton=document.getElementById('install-app-btn');
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;if(installButton)installButton.hidden=false});
installButton?.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installButton.hidden=true});
window.addEventListener('appinstalled',()=>{deferredPrompt=null;if(installButton)installButton.hidden=true});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(err=>console.error('WonderQR service worker registration failed',err)));
window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{
 const b=document.getElementById('admin-push-btn'),s=document.getElementById('admin-push-status'),subt=document.getElementById('admin-push-sub');if(!b)return;
 const U='https://smzwucttkyuqzazozcat.supabase.co',t=new URLSearchParams(location.search).get('token')||localStorage.getItem('admin_auth_token');
 const msg=(x,e=false)=>{if(s){s.textContent=x;s.className='admin-push-status'+(e?' error':'')}};
 const bytes=v=>{const p='='.repeat((4-v.length%4)%4),x=(v+p).replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(x),c=>c.charCodeAt(0))};
 const vapid=async()=>{let k=localStorage.getItem('wonderqr_vapid_public_key');if(k)return k;const r=await fetch(U+'/functions/v1/admin-push-subscription',{headers:{'x-admin-token':t||''}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Unable to contact the push service.');k=d.vapid_public_key||'';if(!k)throw Error('Push service is not configured on the WonderQR server.');localStorage.setItem('wonderqr_vapid_public_key',k);return k};
 b.onclick=async()=>{b.disabled=true;msg('Preparing…');try{if(!t)throw Error('Admin access token is missing.');if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('Push notifications are not supported here.');if(Notification.permission==='denied')throw Error('Notifications are blocked. Open browser site settings and allow notifications.');const p=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(p!=='granted')throw Error('Notification permission was not granted.');const r=await navigator.serviceWorker.ready;let q=await r.pushManager.getSubscription();if(!q)q=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(await vapid())});const z=await fetch(U+'/functions/v1/admin-push-subscription',{method:'POST',headers:{'Content-Type':'application/json','x-admin-token':t},body:JSON.stringify({subscription:q.toJSON(),user_agent:navigator.userAgent})}),d=await z.json().catch(()=>({}));if(!z.ok)throw Error(d.error||'Unable to save this device subscription.');msg('Notifications are enabled for this device.');b.textContent='ON';b.className='admin-push-btn on';if(subt)subt.textContent='This device is subscribed.'}catch(e){msg(e.message||'Unable to enable notifications.',true)}finally{b.disabled=false}};
},0));
