import { SUPABASE_URL } from './config.js';
const urlParams=new URLSearchParams(location.search);const repToken=urlParams.get('rep_token');const api=`${SUPABASE_URL}/functions/v1/sales_api`;
let currentRep=null,generatedCustomerUrl='',generatedOwnerUrl='',currentBizName='';
const urlFields=[['instagram-url','Instagram Profile URL'],['youtube-url','YouTube Channel URL'],['facebook-url','Facebook Page URL'],['justdial-url','Justdial URL'],['pinterest-url','Pinterest Profile URL'],['x-url','X (Twitter) Profile URL']];
const isValidUrl=v=>{try{const u=new URL(v);return u.protocol==='http:'||u.protocol==='https:';}catch{return false;}};const isValidPhone=v=>!v||/^\+?[0-9][0-9\s().-]{8,18}$/.test(v);
const normalizeGoogleReviewInput=v=>{v=String(v||'').trim();if(!v)return '';if(isValidUrl(v))return v;const placeId=v.replace(/^placeid[=:]?/i,'').trim();if(!/^[A-Za-z0-9_-]+$/.test(placeId))return '';return `https://search.google.com/local/writereview?placeid=${encodeURIComponent(placeId)}`;};
function setupGoogleField(){const el=document.getElementById('google-url');if(el){el.type='text';el.placeholder='e.g. ChIJxxxxxxxxxxxxxxxx';const label=el.previousElementSibling;if(label)label.textContent='Google Place ID *';if(!el.nextElementSibling?.dataset.placeHint){const hint=document.createElement('div');hint.dataset.placeHint='true';hint.className='pin-note';hint.textContent='Enter only the Google Place ID. Existing full Google Review URLs are also accepted.';el.parentNode.insertBefore(hint,el.nextSibling);}}}
function setupQrField(){const el=document.getElementById('qr-code');if(el)el.addEventListener('blur',()=>{el.value=el.value.trim().toUpperCase();});}
function validateOptionalLinks(){for(const[id,label]of urlFields){const el=document.getElementById(id),v=el?.value.trim()||'';if(v&&!isValidUrl(v)){alert(`${label} must be a valid http(s) URL.`);el.focus();return false;}}for(const[id,label]of [['whatsapp','WhatsApp Number'],['phone','Phone Number']]){const el=document.getElementById(id),v=el?.value.trim()||'';if(v&&!isValidPhone(v)){alert(`${label} must be a valid phone number.`);el.focus();return false;}}return true;}
async function call(action,extra={}){const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json','x-rep-token':repToken},body:JSON.stringify({action,rep_token:repToken,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
async function init(){setupGoogleField();setupQrField();const a=document.getElementById('agent-info');if(!repToken){a.innerText='Error: Missing sales token link.';document.getElementById('onboard-form').style.display='none';return;}try{const d=await call('profile');currentRep=d.rep;a.innerText=`Sales Agent: ${d.rep.rep_name}`;}catch(e){a.innerText=e.message;document.getElementById('onboard-form').style.display='none';}}
window.copyCustomerUrl=async()=>{if(generatedCustomerUrl){await navigator.clipboard.writeText(generatedCustomerUrl);alert('Customer Review Link copied!');}};window.copyOwnerUrl=async()=>{if(generatedOwnerUrl){await navigator.clipboard.writeText(generatedOwnerUrl);alert('Owner Dashboard Link copied!');}};
window.shareCustomerUrl=()=>{if(generatedCustomerUrl)window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(`Here is your Customer Review QR Link: ${generatedCustomerUrl}`)}`,'_blank');};window.shareOwnerUrl=()=>{if(generatedOwnerUrl)window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(`Here is your Private Business Owner Dashboard Link: ${generatedOwnerUrl}`)}`,'_blank');};
window.generateCustomerQr=()=>{if(!generatedCustomerUrl)return;const modal=document.getElementById('qr-modal'),container=document.getElementById('qr-canvas-container');document.getElementById('qr-modal-title').innerText=`${currentBizName||'Customer'} QR Code`;document.getElementById('qr-modal-url').innerText=generatedCustomerUrl;container.innerHTML='';new QRCode(container,{text:generatedCustomerUrl,width:200,height:200,colorDark:'#000',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.H});setTimeout(()=>{const img=container.querySelector('img'),canvas=container.querySelector('canvas'),d=document.getElementById('download-qr-btn');if(img?.src)d.href=img.src;else if(canvas)d.href=canvas.toDataURL('image/png');},150);modal.classList.remove('hidden');modal.style.display='flex';};
document.getElementById('close-qr-modal-btn')?.addEventListener('click',()=>{const m=document.getElementById('qr-modal');m.classList.add('hidden');m.style.display='none';});document.getElementById('onboard-another-btn')?.addEventListener('click',()=>{document.getElementById('onboard-form').reset();setupGoogleField();setupQrField();document.getElementById('onboard-form').classList.remove('hidden');document.getElementById('success-container').classList.add('hidden');});
document.getElementById('onboard-form')?.addEventListener('submit',async e=>{e.preventDefault();if(!currentRep)return alert('Sales Rep not authenticated!');const qrCode=document.getElementById('qr-code').value.trim().toUpperCase(),bizName=document.getElementById('biz-name').value.trim(),googleInput=document.getElementById('google-url').value.trim(),googleUrl=normalizeGoogleReviewInput(googleInput),ownerName=document.getElementById('owner-name').value.trim(),pin=document.getElementById('admin-pin').value.trim(),pin2=document.getElementById('admin-pin-confirm').value.trim();if(!qrCode)return alert('Enter the Standee Code (QR ID).');if(!/^\d{4}$/.test(pin)||pin!==pin2)return alert('Admin PIN must be exactly 4 digits and both PIN entries must match.');if(!googleUrl){alert('Enter a valid Google Place ID or a complete Google Review URL.');document.getElementById('google-url').focus();return;}if(!validateOptionalLinks())return;try{const d=await call('onboard',{qr_code:qrCode,business_name:bizName,google_review_url:googleUrl,owner_name:ownerName,pin,whatsapp_number:document.getElementById('whatsapp').value.trim()||null,phone_number:document.getElementById('phone').value.trim()||null,instagram_url:document.getElementById('instagram-url').value.trim()||null,youtube_url:document.getElementById('youtube-url').value.trim()||null,facebook_url:document.getElementById('facebook-url').value.trim()||null,justdial_url:document.getElementById('justdial-url').value.trim()||null,pinterest_url:document.getElementById('pinterest-url').value.trim()||null,x_url:document.getElementById('x-url').value.trim()||null});const baseUrl=`${location.origin}/wonderqr`;generatedCustomerUrl=`${baseUrl}/?qr=${encodeURIComponent(qrCode)}`;generatedOwnerUrl=`${baseUrl}/admin.html?token=${encodeURIComponent(d.business.auth_token)}`;currentBizName=bizName;document.getElementById('created-customer-url').value=generatedCustomerUrl;document.getElementById('created-owner-url').value=generatedOwnerUrl;document.getElementById('onboard-form').classList.add('hidden');document.getElementById('success-container').classList.remove('hidden');}catch(e){console.error(e);alert('Failed to onboard business: '+e.message);}});init();