-- Full Supabase Setup Script with Sales Rep & Social/Review Link Support

create table qr_codes (
    id bigint generated by default as identity primary key,
    code text unique not null,
    status text default 'available' check (status in ('available', 'assigned', 'disabled')),
    created_at timestamptz default now()
);

create table sales_reps (
    id bigint generated by default as identity primary key,
    rep_name text not null,
    access_token uuid default gen_random_uuid() not null unique,
    active boolean default true,
    created_at timestamptz default now()
);

create table businesses (
    id bigint generated by default as identity primary key,
    qr_code_id bigint references qr_codes(id) on delete restrict,
    sales_rep_id bigint references sales_reps(id),
    business_name text not null,
    google_review_url text not null,
    instagram_url text,
    youtube_url text,
    facebook_url text,
    whatsapp_number text,
    phone_number text,
    justdial_url text,
    pinterest_url text,
    x_url text,
    owner_name text,
    auth_token uuid default gen_random_uuid() not null,
    active boolean default true,
    created_at timestamptz default now()
);

create table feedback (
    id bigint generated by default as identity primary key,
    business_id bigint not null references businesses(id) on delete cascade,
    rating integer not null check (rating between 1 and 3),
    message text,
    created_at timestamptz default now()
);

create table sales_records (
    id bigint generated by default as identity primary key,
    business_id bigint not null references businesses(id) on delete restrict,
    sales_rep_id bigint not null references sales_reps(id) on delete restrict,
    sale_date timestamptz not null default now(),
    selling_price numeric(12,2) not null check (selling_price >= 0),
    incentive_amount numeric(12,2) not null default 0 check (incentive_amount >= 0),
    created_at timestamptz not null default now()
);

create index sales_records_rep_date_idx on sales_records (sales_rep_id, sale_date desc);
create index sales_records_business_idx on sales_records (business_id);

alter table qr_codes enable row level security;
alter table sales_reps enable row level security;
alter table businesses enable row level security;
alter table feedback enable row level security;
alter table sales_records enable row level security;

create policy "Public can read active businesses" on businesses for select using (active = true);
create policy "Public can submit feedback" on feedback for insert with check (rating between 1 and 3);
create policy "Owners read feedback with auth_token" on feedback for select using (business_id in (select id from businesses where auth_token::text = current_setting('request.headers', true)::json->>'x-owner-token'));
create policy "Sales reps read active token" on sales_reps for select using (access_token::text = current_setting('request.headers', true)::json->>'x-rep-token');
create policy "Sales reps read qr_codes" on qr_codes for select using (status = 'available');
create policy "Sales reps update qr_codes" on qr_codes for update using (exists (select 1 from sales_reps where access_token::text = current_setting('request.headers', true)::json->>'x-rep-token'));
create policy "Sales reps insert businesses" on businesses for insert with check (sales_rep_id in (select id from sales_reps where access_token::text = current_setting('request.headers', true)::json->>'x-rep-token'));

insert into sales_reps (rep_name) values ('Rahul Sales');
insert into qr_codes (code, status) values ('RS00001', 'available'), ('RS00002', 'available');
