create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  event_type text not null check (event_type in ('scan','rating_1','rating_2','rating_3','instagram_click','youtube_click','facebook_click','pinterest_click','x_click','whatsapp_click','phone_click','justdial_click')),
  visitor_id text,
  created_at timestamptz not null default now()
);

create index if not exists usage_events_business_created_idx on public.usage_events (business_id, created_at desc);
create index if not exists usage_events_business_type_created_idx on public.usage_events (business_id, event_type, created_at desc);

alter table public.usage_events enable row level security;
revoke all on table public.usage_events from anon, authenticated;
revoke all on sequence public.usage_events_id_seq from anon, authenticated;
