create table public.sales_records (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete restrict,
  sales_rep_id bigint not null references public.sales_reps(id) on delete restrict,
  sale_date timestamptz not null default now(),
  selling_price numeric(12,2) not null check (selling_price >= 0),
  incentive_amount numeric(12,2) not null default 0 check (incentive_amount >= 0),
  created_at timestamptz not null default now()
);

alter table public.sales_records enable row level security;

create index sales_records_rep_date_idx on public.sales_records (sales_rep_id, sale_date desc);
create index sales_records_business_idx on public.sales_records (business_id);

comment on table public.sales_records is 'Sales snapshots used for sales-rep performance and incentive reporting. Written by trusted Edge Functions.';
comment on column public.sales_records.selling_price is 'Actual price charged for this sale.';
comment on column public.sales_records.incentive_amount is 'Actual incentive assigned to the sales rep for this sale.';
